language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t Bri997/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true Bri997/react-test npm test

after_success:
  - docker build -t Bri997/multi-client ./client
  - docker build -t Bri997/multi-nginx ./nginx
  - docker build -t Bri997/multi-server ./server
  - docker build -t Bri997/multi-worker ./worker
 
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Take these images and push them to docker hub
  - docker push Bri997/multi-client
  - docker push Bri997/multi-nginx
  - docker push Bri997/multi-server
  - docker push Bri997/multi-worker
