language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t brian997/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true brian997/react-test npm test

after_success:
  - docker build -t brian997/multi-client ./client
  - docker build -t brian997/multi-nginx ./nginx
  - docker build -t brian997/multi-server ./server
  - docker build -t brian997/multi-worker ./worker
 
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Take these images and push them to docker hub
  - docker push brian997/multi-client
  - docker push brian997/multi-nginx
  - docker push brian997/multi-server
  - docker push brian997/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: MutiDocker
  env: MutiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-738786693903
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

  